### ISSUE TITLE
ServiceStack referenced as an assembly

### ISSUE THREAD

**Issue by claq2** [NetCoreTemplates/mvcidentityserver#1]
In the Identity and main MVC project, the ServiceStack reference is an assembly reference with a hint path to somewhere on mythz's hard drive. I'm guessing the should actually be NuGet references. When I changed to use Nuget it built.

**Comment by mythz** [comment]
They must've been added by Rider instead of using the CI packages, should be resolved with this commit: https://github.com/NetCoreTemplates/mvcidentityserver/commit/05e151572e78c947c5bcc06518a2bc1a62c89793

thx for reporting!
