### ISSUE TITLE
External web library "lib" folder missing from IdentityServer wwwroot

### ISSUE THREAD

**Issue by claq2** [NetCoreTemplates/mvcidentityserver#2]
The wwwroot/lib folder is missing from the IdentityServer project, so no bootstrap or jquery files are available. The IdentityService UI is functional, but not very pretty.

**Comment by mythz** [comment]
Ahh thanks, it was being ignored in .gitignore, should be resolved in this commit https://github.com/NetCoreTemplates/mvcidentityserver/commit/4fc1e93e51f33010c76d81eb227224e1f40c7b7f

Should now be resolved in new projects.

thx for reporting!
