### ISSUE TITLE
Startup does not inherit from ModularStartup

### ISSUE THREAD

**Issue by visschersm** [NetCoreTemplates/mvcidentityserver#3]
When trying to run this code sample I run into some issues:

`public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(builder =>
                {
                    builder.UseModularStartup<Startup>();
                });`

`public class Startup
    {
        ...
    }`

The startup used does not inherit from ModularStartup.
This is the case for both the MyApp + MyApp.Api

After altering this I cannot seem to connect to the Api with the App though they are running now. I only get 404 responses.
Is there documentation on how I should use this example?
I want to implement this in my own app but cannot check if the examples are not working.

**Comment by mythz** [comment]
This template shouldn't use ModularStartup which I've resolved in [this commit](https://github.com/NetCoreTemplates/mvcidentityserver/commit/72b6cb562c7c531151fd7d5af302054aefb3bd95) which will be available in the next time you create a template from it.

I've quickly tested the Auth & see issues signing in, I'll investigate which bit rot is causing it to fail tomorrow.

I'll respond with any updates in the [Customer Forums Thread](https://forums.servicestack.net/t/servicestack-and-identityserver4-internalservererror/8942).

**Comment by mythz** [comment]
The [workaround to handle Chrome's new SameSite Cookies Policy](https://forums.servicestack.net/t/servicestack-and-identityserver4-internalservererror/8942) should now be supported in new templates:

    $ x new mvcidentityserver ProjectName

**Comment by visschersm** [comment]
The change made to the template does not effect my test case implementation.

I've made this [Test repository](https://github.com/visschersm/HopTea) which implements the minimal servicestack with the QuickStart from [Identity Server](https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html). With AspNetCore I can get my authorized request to work by accepting all the tokens, but when I change the controller to a ServiceStack request I cannot get it to work.

Looking at the quickstart this should accept all the tokens.

`services.AddAuthentication("Bearer")
            .AddJwtBearer("Bearer", options =>
            {
                options.Authority = "https://localhost:5001";

                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateAudience = false
                };
            });`

**Comment by mythz** [comment]
To avoid continued duplication please only report issues in a single location, continuing on the Customer Forums: 
https://forums.servicestack.net/t/servicestack-and-identityserver4-internalservererror/8942
