### ISSUE TITLE
Correct way to run?

### ISSUE THREAD

**Issue by MikeOtown** [NetCoreTemplates/mvcidentityserver#4]
What is the correct way to run this solution in Visual Studio?  I'm getting an error page (see screenshot)

![image](https://user-images.githubusercontent.com/18534728/103570195-a0840680-4e96-11eb-8880-3b0470468ef4.png)

**Comment by mythz** [comment]
All 3 Host Projects need to run, starting with the [IdentityServer](https://github.com/NetCoreTemplates/mvcidentityserver/tree/master/IdentityServer) instance then the MyApp [Web](https://github.com/NetCoreTemplates/mvcidentityserver/tree/master/MyApp) and [Web APIs](https://github.com/NetCoreTemplates/mvcidentityserver/tree/master/MyApp.Api) projects.
