### ISSUE TITLE
Trying to integrate with our IdentityServer

### ISSUE THREAD

**Issue by MikeOtown** [NetCoreTemplates/mvcidentityserver#5]
I retrieved an access_token from my Identity Server's connect/token endpoint.  I then construct a request in Postman for https://localhost:5001/requiresauth and on the Authorization tab select Type = Bearer Token and paste in the token.  When I execute the GET request I get "ECONNREFUSED".

**Comment by MikeOtown** [comment]
Now I'm getting a 404:

![image](https://user-images.githubusercontent.com/18534728/103582740-79d0ca80-4eac-11eb-8c19-a1564782d24b.png)

**Comment by mythz** [comment]
You're hitting the wrong endpoint, 5001 is the .Api project, the Web App and ServiceStack Services are on 5002.

**Comment by MikeOtown** [comment]
So what endpoints are on 5001?

**Comment by MikeOtown** [comment]
Also, do I need the MVC project?  What if I just want an API project?
