### ISSUE TITLE
requiresauth

### ISSUE THREAD

**Issue by MikeOtown** [NetCoreTemplates/mvcidentityserver#6]
When I request /requiresauth with a Bearer Token, it redirects to localhost:5002/Account/Login

![image](https://user-images.githubusercontent.com/18534728/103662522-0e373d80-4f3e-11eb-9a9a-d25b73c573b9.png)

**Comment by MikeOtown** [comment]
Here is the Bearer token I'm using...

![image](https://user-images.githubusercontent.com/18534728/103663101-b9e08d80-4f3e-11eb-94aa-604ea90cb2b2.png)

**Comment by mythz** [comment]
Please reserve issues to bugs with the template, you can view your support options on your Customer Support page https://servicestack.net/account/support

We also don't provide any support for 3rd Party software like Identity Server, you'd need to seek support from the 3rd Party software vendor directly.

**Comment by MikeOtown** [comment]
I don't have an account.  Can you please help me get this working.  You're the only person who supports ServiceStack.

**Comment by mythz** [comment]
If you want to use and get support for IdentityServer, don't use ServiceStack, use their templates directly:
https://identityserver4.readthedocs.io/en/latest/quickstarts/0_overview.html

**Comment by MikeOtown** [comment]
I want support for ServiceStack working with IdentityServer.  Our IdentityServer works fine.
